spring:
  application:
    name: ringo-boot-sample
  messages:
    encoding: UTF-8
    fallback-to-system-locale: false
  mvc:
    problemdetails:
      enabled: true
  data:
    redis:
#      url: ${REDIS_URL:redis://47.97.104.166:6379}
      host: 47.97.104.166
      port: 6379
      database: 0
      password: lGHlxrSL+hhWNBdNnqNYuFZT34OsCaqrj+OYhyFnzBY=
server:
  port: 8080
ringo:
  boot:
    problem:
      enabled: true
      i18n: true
      handlers:
        application: true
        mvc: true
        verification: true
        fallback: true
    verification:
      enabled: true
      store: redis
      length: 6
      ttl: 5m
      max-attempts: 5
      issue-rate-limit:
        interval: 60s
        rules:
          - id: application-hour
            scope: global
            max-issues: 1000
            window: 1h
          - id: account-email-verification-subject-hour
            scope: subject
            namespace: account
            purpose: email-verification
            max-issues: 10
            window: 1h
      redis:
        secret: v2pd/5bgDhCt81RaMcfAVC+nFYHNn/EMJdvmFo2dyEo=
        expired-retention: 1m
