spring:
  application:
    name: ringo-boot-sample
  messages:
    encoding: UTF-8
    fallback-to-system-locale: false
  mvc:
    problemdetails:
      enabled: true
server:
  port: 8080
ringo:
  boot:
    problem:
      enabled: true
      application-enabled: true
      mvc-enabled: true
      i18n-enabled: true
      fallback-enabled: true
    verification:
      enabled: true
      length: 6
      ttl: 5m
      max-attempts: 5
      resend-interval: 60s
      email:
        console-enabled: true
      sms:
        console-enabled: true
