spring:
  application:
    name: spring-commons-sample
  messages:
    encoding: UTF-8
    fallback-to-system-locale: false
  mvc:
    problemdetails:
      enabled: true
server:
  port: 8080
ringotangs:
  spring-commons:
    web:
      exception-handler:
        enabled: true
        i18n-enabled: true
